ARG base_img=ste93/mbvm:simpar2025
FROM $base_img
LABEL maintainer="Stefano Bernagozzi"
USER user1
RUN bash -c "rm /home/user1/MBVM-SIMPAR2025/monitoring/prop2.py"
COPY monitoring/prop2.py /home/user1/MBVM-SIMPAR2025/monitoring/prop2.py